### ISSUE TITLE
rewrite jetpack and starterkit as a modules

### ISSUE THREAD

**Issue by 1wheel** [1wheel/d3-jetpack-module#1]
- [x] translate selection
- [ ] translate transition
- [x] tspans
- [x] append
- [x] insert
- [x] parseAttributes
- [x] wordwrap
- [x] ascendingKey
- [x] descendingKey
- [x] ƒ
- [x] d3_selection_on
- [ ] prop
- [x] appendMany
- [x] attachTooltip
- [x] conventions
- [x] selectAppend

**Comment by aubergene** [comment]
Once these are complete, will you apply to get it moved to the d3 github org?

**Comment by 1wheel** [comment]
Don't think so, no - it is on the wiki and tagged on npm:
- https://github.com/d3/d3/wiki/Plugins
- https://www.npmjs.com/browse/keyword/d3-module
