### ISSUE TITLE
Change where selection mutations happen

### ISSUE THREAD

**Issue by aubergene** [1wheel/d3-jetpack-module#12]
If I want to just import `selectAppend` 

``` js
import {selectAppend} from 'd3-jetpack-module/src/selectAppend'
```

then it won't affect the prototype of `d3.selection` as that's defined in `index.js`. Perhaps that's a good thing, or I shouldn't be importing that like?

**Comment by aubergene** [comment]
Hmm, actually perhaps this is just more of an issue about how roll up works, this issue and other related ones. https://github.com/rollup/rollup/issues/305

I guess if the above import is valid, then it probably should add itself to d3.selection within the function.

**Comment by 1wheel** [comment]
I followed this example: https://github.com/d3/d3-selection-multi/blob/master/index.js

I think you could do `d3.selection.prototype.selectAppend = selectAppend;` in your application code to import it by itself.
