### ISSUE TITLE
Functor and Rebind

### ISSUE THREAD

**Issue by syntagmatic** [1wheel/d3-jetpack-module#14]
d3.functor and d3.rebind have been removed with the entire Internals module for v4.

https://github.com/d3/d3/blob/abdcb7e88d390627d6bc9ab3aec8f182002f647e/CHANGES.md#internals

These are useful utility functions. Perhaps they belong in the Jetpack.

Copied from https://github.com/gka/d3-jetpack/issues/23

**Comment by 1wheel** [comment]
Hmm, maybe we should start a d3-v3-removed project?
- d3.round
- d3.requote
- d3.functor
- d3.rebind
- d3.link

**Comment by 1wheel** [comment]
also d3.transform

https://github.com/d3/d3/blob/v3.5.17/src/math/transform.js
