### ISSUE TITLE
auto add ventor prefix

### ISSUE THREAD

**Issue by 1wheel** [1wheel/d3-jetpack-module#15]
```
// auto add ventor prefix
d3.selection.prototype.stylePrefix = function(name, value, priority){
  this.style('-webkit-' + name, value, priority)
  this.style('-moz-' +    name, value, priority)
  this.style('-ms-' +     name, value, priority)
  this.style(             name, value, priority)

  return this
}

d3.select('body').stylePrefix('text-stroke', '2px steelblue')
```

**Comment by gka** [comment]
not that easy unfortunately. some properties have different names in different browsers, and some even use different values! let's not go there and instead recommend [autoprefixer](https://github.com/postcss/autoprefixer) post-css filter.

**Comment by gka** [comment]
btw, [this](https://github.com/postcss/autoprefixer/blob/master/data/prefixes.coffee) seems to be the data file autoprefixer is using. we don't want all that junk in here, right?

**Comment by 1wheel** [comment]
ug, why is everything so complicated?
