### ISSUE TITLE
add rollup step to repo

### ISSUE THREAD

**Issue by 1wheel** [1wheel/d3-jetpack-module#7]

**Comment by aubergene** [comment]
I'm trying to bundle using Rollup so that D3 is left as an external dependency but d3-jetpack-module is bundled within myModule. It's not working and I know you love solving other people's problems ;)  so here's rollup config. Perhaps I'm doing it all wrong or shouldn't be trying to do this at all.

``` js
import node from 'rollup-plugin-node-resolve';

export default {
  entry: 'index.js',
  plugins: [
    node({
      jsnext: true,
      skip: [ 'd3' ],
    }),
  ],
  globals: {
    d3: 'd3'
  },
  moduleName: 'myModule',
  targets: [
    { dest: 'myModule.js', format: 'umd' }
  ]
}
```

**Comment by 1wheel** [comment]
I have no idea! This is what I'm using to generate `d3v4+jetpack.js`: https://github.com/1wheel/d3/blob/jetpack/index.js

That should be included in this repo, but I haven't figured out where the second index.js should go.

**Comment by 1wheel** [comment]
@aubergene do you have your myModule repo sitting anywhere public?

**Comment by 1wheel** [comment]
I think this is working now after adding the [build step](https://github.com/1wheel/d3-jetpack-module/blob/master/bin/rollup) to repo. 

This [bl.ock](http://bl.ocks.org/1wheel/b9b710ba9a1b26a2eaa6c56bfc2b2bb2) might help you make a custom build with rollup.
